### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by afang** [ukupat/trolol#1]
```
module.js:338
    throw err;
          ^
Error: Cannot find module '/usr/local/lib/src/os-specific/trolol-mac.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/trolol/src/trolol.js:5:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
------------------------------------------------------------```

**Comment by pete101011** [comment]
Yeah I got the same thing. The base path doesn't come with the right path. 

Had to manually change things, and even then some things like os-specific operations don't work.

**Comment by ukupat** [comment]
Can you tell me what version are you guys running?

**Comment by ukupat** [comment]
It seems that the problem is solved
