### ISSUE TITLE
npm ERR

### ISSUE THREAD

**Issue by DMarinsa** [ukupat/trolol#17]
I guess this has been abandoned but when I try to install trolol through npm in my own machine I get 

/usr/bin/trolol -> /usr/lib/node_modules/trolol/trolol

> wmi-client@0.2.0 install /usr/lib/node_modules/trolol/node_modules/wmi-client
> node scripts/install.js

fs.js:1123
  return binding.chmod(pathModule._makeLong(path), modeNum(mode));
                 ^

Error: EPERM: operation not permitted, chmod '/usr/lib/node_modules/trolol/node_modules/wmi-client/bin/wmic_centos_x64'
    at Object.fs.chmodSync (fs.js:1123:18)
    at Object.<anonymous> (/usr/lib/node_modules/trolol/node_modules/wmi-client/scripts/install.js:5:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wmi-client@0.2.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wmi-client@0.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/david/.npm/_logs/2018-07-07T18_35_05_715Z-debug.log

**Comment by marcelobbfonseca** [comment]
i got this error running on Ubuntu 16
